#!/bin/bash
####################################
# GWAS Analysis for Multiple Chromosomes #
####################################
#$ -N gwas_SHS_covar       # Job name
#$ -pe smp 4               # Set the processing environment and number of cores (adjust as needed)
#$ -l h_vmem=8G            # Set the max memory needed
#$ -l mem_free=8G          # Set the amount of RAM necessary for the job to run
#$ -l h_rt=10:0:0          # Set hard runtime limit hh:mm:ss (adjust as needed)
#$ -l s_rt=8:0:0           # Set soft runtime limits hh:mm:ss (adjust as needed)
#$ -cwd                    # Execute job from current working directory
#$ -j y                    # Join stdout and stderr
#$ -o $JOB_NAME_$JOB_ID.out # Output log file
#$ -e $JOB_NAME_$JOB_ID.err # Output error file
#$ -M carissa.sherman@cuanschutz.edu # Email to receive updates about job status
#$ -m bea                  # When to receive emails: begin (b), error (e), abort (a), suspend (s)

#################################
# COMMANDS FOR RUNNING THE JOB  #
#################################
# Activate the conda environment with PLINK installed
source "${HOME}/miniforge3/etc/profile.d/conda.sh"
conda activate plink_tutorial

# Define input and output directories
input_dir="/master/csherman/SHS_GWAS/SHSph2_data/vcf/plink/"
output_dir="results"

# Create output directory if it doesn't exist
mkdir -p ${output_dir}

# Set the number of OpenMP threads to use
export OMP_NUM_THREADS=1

# Define phenotype and covariate files
pheno_file="filtered_pheno_samp_20240728.txt"
covar_file="filtered_covar_pc.txt"

# Set the number of OpenMP threads to use
export OMP_NUM_THREADS=1

# Loop over chromosomes
for i in {1..22}; do
  echo "Running GWAS for chromosome ${i}"
  plink --bfile ${input_dir}chr${i} --linear --pheno ${pheno_file} --pheno-name logNMR --covar ${covar_file} --covar-name S2AGE b_Gender BMIcalc PC1 PC2 PC3 PC4 PC5 PC6 PC7 PC8 PC9 PC10 --allow-no-sex --out ${output_dir}/gwas_results_chr${i}
  if [ $? -ne 0 ]; then
    echo "GWAS for chromosome ${i} failed"
    exit 1
  fi
  echo "GWAS for chromosome ${i} completed"
done

# Combine results
# Create header
head -n 1 ${output_dir}/gwas_results_chr1.assoc.linear > ${output_dir}/gwas_combined_results.assoc.linear

# Append results
for i in {1..22}; do
  tail -n +2 ${output_dir}/gwas_results_chr${i}.assoc.linear >> ${output_dir}/gwas_combined_results.assoc.linear
done

# Bonferroni correction
awk 'NR==1 || $9 < 0.00000005' ${output_dir}/gwas_combined_results.assoc.linear > ${output_dir}/gwas_combined_results_sig_20240722.txt

# Deactivate conda environment
conda deactivate
