#!/bin/bash
####################################
# GWAS ANALYSIS V. 3 20240730      #
####################################
#$ -N gwas_v3           # Job name
#$ -pe smp 1               # Set the processing environment and number of cores
#$ -l h_vmem=8G            # Set the max memory needed. If the max is exceeded the job will abort
#$ -l mem_free=8G          # Set the amount of RAM necessary for the job to run
#$ -l h_rt=4:0:0           # Set hard runtime limit hh:mm:ss. Job will abort once this limit is hit
#$ -l s_rt=3:45:0          # Set soft runtime limits hh:mm:ss. Job will send a warning once this limit is hit
#$ -cwd                    # Execute job from current working directory
#$ -j y                    # Join stdout and stderr
#$ -o $JOB_NAME_$JOB_ID.out # Output log file
#$ -e $JOB_NAME_$JOB_ID.err # Output error file
#$ -M carissa.sherman@cuanschutz.edu # Email to receive updates about job status
#$ -m bea                  # When to receive emails: begin (b), error (e), abort (a), suspend (s)

#################################
# COMMANDS FOR RUNNING THE JOB  #
#################################
# Activate the conda environment with PLINK installed
source "${HOME}/miniforge3/etc/profile.d/conda.sh"
conda activate plink_tutorial

# Define input and output directories
input_dir="/master/csherman/SHS_GWAS/SHSph2_data/vcf/plink/"
output_dir="results"

# Create output directory if it doesn't exist
mkdir -p ${output_dir}

# Loop over chromosomes
for i in {1..22}; do
  echo "Running GWAS for chromosome ${i}"
  plink --bfile ${input_dir}chr${i} --linear --pheno SHSph2_pheno_clean20240723CS.txt --pheno-name logNMR --covar SHSph2_covariates_clean20240723CS.txt --out ${output_dir}/gwas_results_chr${i}
  echo "GWAS for chromosome ${i} completed"
done

# Combine results
# Create header
head -n 1 ${output_dir}/gwas_results_chr1.assoc.linear > ${output_dir}/gwas_combined_results.assoc.linear

# Append results
for i in {1..22}; do
  tail -n +2 ${output_dir}/gwas_results_chr${i}.assoc.linear >> ${output_dir}/gwas_combined_results.assoc.linear
done

# Bonferroni correction
awk 'NR==1 || $9 < 0.00000005' ${output_dir}/gwas_combined_results.assoc.linear > ${output_dir}/gwas_combined_results_sig_20240722.txt

# Deactivate conda environment
conda deactivate
